apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiServer.namePrefix }}-external
  labels:
    {{- include "smallest-self-host.labels" . | nindent 4 }}
    app: {{ .Values.apiServer.namePrefix }}
spec:
  selector:
    app: {{ .Values.apiServer.namePrefix }}
    {{- include "smallest-self-host.selectorLabels" . | nindent 6 }}
  type: {{ .Values.apiServer.service.type | default "ClusterIP" }}
  {{- if and (eq .Values.apiServer.service.type "LoadBalancer") .Values.api.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range .Values.apiServer.service.loadBalancerSourceRanges }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if and (eq .Values.apiServer.service.type "LoadBalancer") .Values.apiServer.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.apiServer.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.apiServer.port }}
      targetPort: {{ .Values.apiServer.port }}
