apiVersion: v2
name: smallest-self-host
description: Helm chart for self hosting Smallest AI's TTS and STT Models

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: redis
    version: "^24.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: gpu-operator
    version: "^24.3.0"
    repository: "https://helm.ngc.nvidia.com/nvidia"
    condition: gpu-operator.enabled
  - name: cluster-autoscaler
    version: "^9.37.0"
    repository: "https://kubernetes.github.io/autoscaler"
    condition: cluster-autoscaler.enabled
  - name: kube-prometheus-stack
    version: "^60.2.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: kube-prometheus-stack.includeDependency,scaling.auto.enabled
  - name: prometheus-adapter
    version: "^4.10.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus-adapter.includeDependency,scaling.auto.enabled
