apiVersion: v1
entries:
  cluster-autoscaler:
  - apiVersion: v2
    appVersion: 1.34.1
    created: "2025-12-01T14:38:06.512957+05:30"
    description: Scales Kubernetes worker nodes within autoscaling groups.
    digest: e4746b4e509473019cf935553e5a7d1315eb5a608fc70ce9d042f9d14fd6f9e9
    home: https://github.com/kubernetes/autoscaler
    icon: https://github.com/kubernetes/kubernetes/raw/master/logo/logo.png
    maintainers:
    - email: guyjtempleton@googlemail.com
      name: gjtempleton
    name: cluster-autoscaler
    sources:
    - https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler
    type: application
    urls:
    - http://localhost:8080/charts/cluster-autoscaler-9.52.1.tgz
    version: 9.52.1
  gpu-operator:
  - apiVersion: v2
    appVersion: v24.9.2
    created: "2025-12-01T14:38:06.514645+05:30"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: v0.16.6
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: a55ca5dfe924b8fb6d0e54d9b35ac29a4ce32515e6fbc762cbb2e7209ffcf79f
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - http://localhost:8080/charts/gpu-operator-v24.9.2.tgz
    version: v24.9.2
  kube-prometheus-stack:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
        - name: Upstream Project
          url: https://github.com/prometheus-operator/kube-prometheus
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: v0.74.0
    created: "2025-12-01T14:38:06.527071+05:30"
    dependencies:
    - condition: crds.enabled
      name: crds
      repository: ""
      version: 0.0.0
    - condition: kubeStateMetrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 5.20.*
    - condition: nodeExporter.enabled
      name: prometheus-node-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.36.*
    - condition: grafana.enabled
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 8.2.*
    - condition: windowsMonitoring.enabled
      name: prometheus-windows-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 0.3.*
    description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards,
      and Prometheus rules combined with documentation and scripts to provide easy
      to operate end-to-end Kubernetes cluster monitoring with Prometheus using the
      Prometheus Operator.
    digest: f62a3296034d36ab197206e5c9fb8976cafd5bfb50ca1ced21a6f112f45428f3
    home: https://github.com/prometheus-operator/kube-prometheus
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    keywords:
    - operator
    - prometheus
    - kube-prometheus
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - email: andrew@quadcorps.co.uk
      name: andrewgkew
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: github.gkarthiks@gmail.com
      name: gkarthiks
    - email: kube-prometheus-stack@sisti.pt
      name: GMartinez-Sisti
    - email: github@jkroepke.de
      name: jkroepke
    - email: scott@r6by.com
      name: scottrigby
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: quentin.bisson@gmail.com
      name: QuentinBisson
    name: kube-prometheus-stack
    sources:
    - https://github.com/prometheus-community/helm-charts
    - https://github.com/prometheus-operator/kube-prometheus
    type: application
    urls:
    - http://localhost:8080/charts/kube-prometheus-stack-60.5.0.tgz
    version: 60.5.0
  prometheus-adapter:
  - apiVersion: v1
    appVersion: v0.12.0
    created: "2025-12-01T14:38:06.527517+05:30"
    description: A Helm chart for k8s prometheus adapter
    digest: fc5c41c9792a8332664a9723ec3d5a5009e28921c21315ad315283eb61c0f990
    home: https://github.com/kubernetes-sigs/prometheus-adapter
    keywords:
    - hpa
    - metrics
    - prometheus
    - adapter
    maintainers:
    - email: mattias.gees@jetstack.io
      name: mattiasgees
      url: https://github.com/mattiasgees
    - name: steven-sheehy
      url: https://github.com/steven-sheehy
    - email: hfernandez@mesosphere.com
      name: hectorj2f
      url: https://github.com/hectorj2f
    name: prometheus-adapter
    sources:
    - https://github.com/kubernetes/charts
    - https://github.com/kubernetes-sigs/prometheus-adapter
    urls:
    - http://localhost:8080/charts/prometheus-adapter-4.14.2.tgz
    version: 4.14.2
  redis:
  - annotations:
      fips: "true"
      images: |
        - name: kubectl
          version: 1.34.2
          image: registry-1.docker.io/bitnami/kubectl:latest
        - name: os-shell
          version: "5"
          image: registry-1.docker.io/bitnami/os-shell:latest
        - name: redis
          version: 8.4.0
          image: registry-1.docker.io/bitnami/redis:latest
        - name: redis-exporter
          version: 1.80.0
          image: registry-1.docker.io/bitnami/redis-exporter:latest
        - name: redis-sentinel
          version: 8.4.0
          image: registry-1.docker.io/bitnami/redis-sentinel:latest
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 8.4.0
    created: "2025-12-01T14:38:06.530612+05:30"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.33.2
    description: Redis(R) is an open source, advanced key-value store. It is often
      referred to as a data structure server since keys can contain strings, hashes,
      lists, sets and sorted sets.
    digest: f4080b11069b1baed587a813f9d45f8b09fe56591ad4123696d5f53583ab25b6
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: redis
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/redis
    urls:
    - http://localhost:8080/charts/redis-24.0.0.tgz
    version: 24.0.0
  smallest-self-host:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-01T14:38:06.512094+05:30"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: ^24.0.0
    - condition: gpu-operator.enabled
      name: gpu-operator
      repository: https://helm.ngc.nvidia.com/nvidia
      version: ^24.3.0
    - condition: cluster-autoscaler.enabled
      name: cluster-autoscaler
      repository: https://kubernetes.github.io/autoscaler
      version: ^9.37.0
    - condition: kube-prometheus-stack.includeDependency,scaling.auto.enabled
      name: kube-prometheus-stack
      repository: https://prometheus-community.github.io/helm-charts
      version: ^60.2.0
    - condition: prometheus-adapter.includeDependency,scaling.auto.enabled
      name: prometheus-adapter
      repository: https://prometheus-community.github.io/helm-charts
      version: ^4.10.0
    description: A Helm chart for Kubernetes
    digest: 344155ff0a645a323058adffa453ee29832c9cba2888a182a2b5c37438e2b6a9
    name: smallest-self-host
    type: application
    urls:
    - http://localhost:8080/smallest-self-host-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-01T14:38:06.485671+05:30"
