{{- if and .Values.global.licenseKey (not .Values.global.licenseKeySecretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smallest-self-host.fullname" . }}-license
  labels:
    {{- include "smallest-self-host.labels" . | nindent 4 }}
type: Opaque
stringData:
  license-key: {{ .Values.global.licenseKey | quote }}
{{- end }}
---
{{- if .Values.global.imageCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smallest-self-host.fullname" . }}-registry
  labels:
    {{- include "smallest-self-host.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.global.imageCredentials.registry .Values.global.imageCredentials.username .Values.global.imageCredentials.password .Values.global.imageCredentials.email (printf "%s:%s" .Values.global.imageCredentials.username .Values.global.imageCredentials.password | b64enc) | b64enc }}
{{- end }}

