apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.lightningAsr.namePrefix }}-config
  labels:
    {{- include "smallest-self-host.labels" . | nindent 4 }}
data:
  lightning_asr.toml: |
    [server]
      port = {{ .Values.lightningAsr.port }}
    [model]
      url = "{{ .Values.models.asrModelUrl }}"
      path = "/smallest/models"
      model_name = "{{ .Values.lightningAsr.modelName }}"



