apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.lightningAsr.namePrefix }}
  labels:
    {{- include "smallest-self-host.labels" . | nindent 4 }}
    app: {{ .Values.lightningAsr.namePrefix }}
spec:
  replicas: {{ .Values.scaling.replicas.lightningAsr | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.lightningAsr.namePrefix }}
      {{- include "smallest-self-host.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.lightningAsr.namePrefix }}
        {{- include "smallest-self-host.selectorLabels" . | nindent 8 }}
      {{- with .Values.lightningAsr.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.global.pullSecretRef }}
      imagePullSecrets:
      - name: {{ .Values.global.pullSecretRef }}
      {{- end }}
      containers:
      - name: {{ .Values.lightningAsr.namePrefix }}
        image: {{ .Values.lightningAsr.image }}
        imagePullPolicy: {{ .Values.lightningAsr.imagePullPolicy | default "IfNotPresent" }}
        env:
        - name: LICENSE_KEY
          value: "{{ .Values.global.licenseKey }}"
        ports:
        - name: http
          containerPort: {{ .Values.lightningAsr.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.lightningAsr.port }}
          initialDelaySeconds: {{ .Values.lightningAsr.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.lightningAsr.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.lightningAsr.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.lightningAsr.port }}
          initialDelaySeconds: {{ .Values.lightningAsr.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.lightningAsr.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.lightningAsr.readinessProbe.timeoutSeconds }}
        {{- if .Values.lightningAsr.resources }}
        resources:
          {{- toYaml .Values.lightningAsr.resources | nindent 10 }}
        {{- end }}
      restartPolicy: Always

