{{- if .Values.scaling.auto.enabled }}
{{- if .Values.scaling.auto.lightningAsr.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.lightningAsr.namePrefix }}
  labels:
    {{- include "smallest-self-host.labels" . | nindent 4 }}
    app: {{ .Values.lightningAsr.namePrefix }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.lightningAsr.namePrefix }}
  minReplicas: {{ .Values.scaling.auto.lightningAsr.hpa.minReplicas }}
  maxReplicas: {{ .Values.scaling.auto.lightningAsr.hpa.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metric:
        name: asr_active_requests
      target:
        type: AverageValue
        averageValue: "{{ .Values.scaling.auto.lightningAsr.hpa.targetActiveRequests }}"
  behavior:
    {{- toYaml .Values.scaling.auto.lightningAsr.hpa.behavior | nindent 6 }}
{{- end }}
{{- end }}

