{{- if .Values.scaling.auto.enabled }}
{{- if .Values.scaling.auto.lightningAsr.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.lightningAsr.namePrefix }}
  labels:
    {{- include "smallest-self-host.labels" . | nindent 4 }}
    app: {{ .Values.lightningAsr.namePrefix }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.lightningAsr.namePrefix }}
  minReplicas: {{ .Values.scaling.auto.lightningAsr.hpa.minReplicas }}
  maxReplicas: {{ .Values.scaling.auto.lightningAsr.hpa.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metric:
        name: asr_active_requests
      target:
        type: AverageValue
        averageValue: "{{ .Values.scaling.auto.lightningAsr.hpa.targetActiveRequests }}"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.scaling.auto.lightningAsr.hpa.scaleUpStabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.scaling.auto.lightningAsr.hpa.scaleDownStabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
{{- end }}
{{- end }}

