apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.lightningAsr.namePrefix }}-internal
  labels:
    {{- include "smallest-self-host.labels" . | nindent 4 }}
    app: {{ .Values.lightningAsr.namePrefix }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.lightningAsr.namePrefix }}
    {{- include "smallest-self-host.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.lightningAsr.port }}
    targetPort: {{ .Values.lightningAsr.port }}
    protocol: TCP

