{{- if .Values.models.volumes.aws.efs.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.models.volumes.aws.efs.namePrefix }}-aws-efs-sc
  labels:
{{ include "smallest-self-host.labels" . | indent 4}}
provisioner: efs.csi.aws.com
{{- end }}