{{- if .Values.models.volumes.aws.efs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.models.volumes.aws.efs.namePrefix }}-aws-efs-pvc
  labels:
{{ include "smallest-self-host.labels" . | indent 4}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.models.volumes.aws.efs.namePrefix }}-aws-efs-sc
  resources:
    requests:
      storage: 5Gi
{{- end }}